import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
import App from './App';
import './index.css';
import '@aws-amplify/ui-react/styles.css';

// amplify_outputs.json is generated by `npx ampx sandbox`; use placeholder until then
const outputs = await import('../amplify_outputs.json');
Amplify.configure(outputs.default ?? outputs);

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <Authenticator>
      <App />
    </Authenticator>
  </React.StrictMode>
);
